markdown_ext: "md"

bp: "" # Must be "" in main repo. Forks set this to "neic.no/" to get *.github.io/neic.no/ to render right.

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      path: "news"
      type: "pages"
    values:
      layout: master
      include: generic
      permalink: /:path/:basename.html
  -
    scope:
      type: "pages"
    values:
      layout: master
      include: generic
      permalink: /:path/:basename/
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: master
      include: post
      permalink: /news/:year/:month/:day/:title/

collections:
  activities:
    output: true
    permalink: /:path/
  people:
    output: true
    permalink: /:collection/:path/
